[tool.poetry]
name = "agent"
version = "0.1.0"
description = ""
authors = ["qifuxiao <867225266@qq.com>"]
readme = "README.md"
packages = [{include = "app"}]

[tool.poetry.dependencies]
python = ">=3.11,<3.13"

langgraph = ">=1.0.8,<2.0.0"
langchain = ">=1.2.10,<2.0.0"
langchain-community = ">=0.4.1,<0.5.0"
langchain-deepseek = ">=1.0.1,<2.0.0"
langchain-openai = ">=1.1.9,<2.0.0"
redis = ">=7.1.1,<8.0.0"
fastapi = ">=0.129.0,<0.130.0"
pandas = ">=2.0.0,<3.0.0"
plotly = ">=5.18.0,<6.0.0"
uvicorn = ">=0.40.0,<0.41.0"
psycopg2-binary = ">=2.9.11,<3.0.0"
faiss-cpu = ">=1.13.2,<2.0.0"
locust = ">=2.43.3,<3.0.0"



[build-system]
requires = ["poetry-core>=1.0.0,<2.0.0"]
build-backend = "poetry.core.masonry.api"
